/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 8.2 and the DSP System Toolbox 8.5.
 * Generated on: 03-Apr-2014 18:17:49
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form I, Second-Order Sections
 * Number of Sections  : 1
 * Stable              : Yes
 * Linear Phase        : No
 * Arithmetic          : fixed
 * Numerator           : s32,29 -> [-4 4)
 * Denominator         : s32,30 -> [-2 2)
 * Scale Values        : s32,38 -> [-7.812500e-03 7.812500e-03)
 * Input               : s12,11 -> [-1 1)
 * Output              : s32,31 -> [-1 1)
 * Numerator State     : s16,15 -> [-1 1)
 * Denominator State   : s16,15 -> [-1 1)
 * Numerator Prod      : s48,44 -> [-8 8)
 * Denominator Prod    : s48,45 -> [-4 4)
 * Numerator Accum     : s50,44 -> [-32 32)
 * Denominator Accum   : s50,45 -> [-16 16)
 * Round Mode          : convergent
 * Overflow Mode       : wrap
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * /Applications/MATLAB_R2013b.app/extern/include/tmwtypes.h 
 */
#define MWSPT_NSEC 3
const int NL[MWSPT_NSEC] = { 1,3,1 };
const int32_T NUM[MWSPT_NSEC][3] = {
  {
       3231895,           0,           0 
  },
  {
     536870912,  1073741824,   536870912 
  },
  {
     536870912,           0,           0 
  }
};
const int DL[MWSPT_NSEC] = { 1,3,1 };
const int32_T DEN[MWSPT_NSEC][3] = {
  {
     536870912,           0,           0 
  },
  {
     536870912,  -971169930,   448804003 
  },
  {
     536870912,           0,           0 
  }
};
