-- IIRCoeffs.vhd
-- VHDL package holding LP IIR filter coefficients
-- Carl-Johan Haell - Chalmers University of Technology

-- Autogenerated file. Generated by "SpectoFixed.m"
-- Generated:                   07 April 2014 20:34:26
-- Filter order (N)             2
-- Sample frequency (fs)        96kHz : 
-- Cutoff frequency (fc)        15kHz : 
-- Fractional binary format:    1.31 
-- Stable (1/0)                 1:

library ieee;
use ieee.std_logic_1164.all; 

package IIR_coeffs is  
constant Coeff_b0 : std_logic_vector(31 downto 0) := B"00010111110110000111011101010101"; --b0 = 1.862935e-01
constant Coeff_b1 : std_logic_vector(31 downto 0) := B"00101111101100001110111010101010"; --b1 = 3.725870e-01
constant Coeff_b2 : std_logic_vector(31 downto 0) := B"00010111110110000111011101010101"; --b2 = 1.862935e-01
constant Coeff_a1 : std_logic_vector(31 downto 0) := B"10111101111001100000111000011000"; --a1 = -5.164168e-01
constant Coeff_a2 : std_logic_vector(31 downto 0) := B"00100111001000101010100010010100"; --a2 = 3.057452e-01
constant ScaleValue_0 : std_logic_vector(17 downto 0) := B"011111111111111111"; --ScaleValue_0 = 1
constant ScaleValue_1 : std_logic_vector(17 downto 0) := B"011111111111111111"; --ScaleValue_1 = 1.000000e+00
end IIR_coeffs; 

 
