-- IIRCoeffs.vhd
-- VHDL package holding LP IIR filter coefficients
-- Carl-Johan Haell - Chalmers University of Technology

-- Autogenerated file. Generated by "SpectoFixed.m"
-- Generated:                   07 April 2014 20:33:08
-- Filter order (N)             2
-- Sample frequency (fs)        192kHz : 
-- Cutoff frequency (fc)        15kHz : 
-- Fractional binary format:    1.31 
-- Stable (1/0)                 1:

library ieee;
use ieee.std_logic_1164.all; 

package IIR_coeffs is  
constant Coeff_b0 : std_logic_vector(31 downto 0) := B"00000111111010100111100110011111"; --b0 = 6.184311e-02
constant Coeff_b1 : std_logic_vector(31 downto 0) := B"00001111110101001111001100111110"; --b1 = 1.236862e-01
constant Coeff_b2 : std_logic_vector(31 downto 0) := B"00000111111010100111100110011111"; --b2 = 6.184311e-02
constant Coeff_a1 : std_logic_vector(31 downto 0) := B"10000000000000000000000000000000"; --a1 = -1.246175e+00
constant Coeff_a2 : std_logic_vector(31 downto 0) := B"01000001000011001101110010001000"; --a2 = 5.082050e-01
constant ScaleValue_0 : std_logic_vector(17 downto 0) := B"011111111111111111"; --ScaleValue_0 = 1
constant ScaleValue_1 : std_logic_vector(17 downto 0) := B"011111111111111111"; --ScaleValue_1 = 1.000000e+00
end IIR_coeffs; 

 
