-- IIRCoeffs.vhd
-- VHDL package holding LP IIR filter coefficients
-- Carl-Johan Haell - Chalmers University of Technology

-- Autogenerated file. Generated by "SpectoFixed.m"
-- Generated:                   07 April 2014 18:06:52
-- Filter order (N)             2
-- Sample frequency (fs)        768kHz : 
-- Cutoff frequency (fc)        15kHz : 
-- Fractional binary format:    1.31 
-- Stable (1/0)                 1:

library ieee;
use ieee.std_logic_1164.all; 

package IIR_coeffs is  
constant Coeff_b0 : std_logic_vector(31 downto 0) := B"00000000101000011110110011111101"; --b0 = 4.941581e-03
constant Coeff_b1 : std_logic_vector(31 downto 0) := B"00000001010000111101100111111010"; --b1 = 9.883162e-03
constant Coeff_b2 : std_logic_vector(31 downto 0) := B"00000000101000011110110011111101"; --b2 = 4.941581e-03
constant Coeff_a1 : std_logic_vector(31 downto 0) := B"10000000000000000000000000000000"; --a1 = -1.818842e+00
constant Coeff_a2 : std_logic_vector(31 downto 0) := B"01101011011111011110010100011000"; --a2 = 8.397795e-01
constant ScaleValue_0 : std_logic_vector(17 downto 0) := B"011111111111111111"; --ScaleValue_0 = 1
constant ScaleValue_1 : std_logic_vector(17 downto 0) := B"011111111111111111"; --ScaleValue_1 = 9.999992e-01
end IIR_coeffs; 

 
