-- IIRCoeffs.vhd
-- VHDL package holding LP IIR filter coefficients
-- Carl-Johan Haell - Chalmers University of Technology

-- Autogenerated file. Generated by "SpectoFixed.m"
-- Generated:                   07 April 2014 20:29:56
-- Filter order (N)             2
-- Sample frequency (fs)        384kHz : 
-- Cutoff frequency (fc)        15kHz : 
-- Fractional binary format:    1.31 
-- Stable (1/0)                 1:

library ieee;
use ieee.std_logic_1164.all; 

package IIR_coeffs is  
constant Coeff_b0 : std_logic_vector(31 downto 0) := B"00000010010100110010010000101110"; --b0 = 1.816227e-02
constant Coeff_b1 : std_logic_vector(31 downto 0) := B"00000100101001100100100001011100"; --b1 = 3.632454e-02
constant Coeff_b2 : std_logic_vector(31 downto 0) := B"00000010010100110010010000101110"; --b2 = 1.816227e-02
constant Coeff_a1 : std_logic_vector(31 downto 0) := B"10000000000000000000000000000000"; --a1 = -1.629720e+00
constant Coeff_a2 : std_logic_vector(31 downto 0) := B"01011010011101000100110010101100"; --a2 = 7.066742e-01
constant ScaleValue_0 : std_logic_vector(17 downto 0) := B"011111111111111111"; --ScaleValue_0 = 1
constant ScaleValue_1 : std_logic_vector(17 downto 0) := B"011111111111111111"; --ScaleValue_1 = 9.999999e-01
end IIR_coeffs; 

 
